api:
  dashboard: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: "support@hbdscan.com"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: "web"

log:
  level: "INFO"
