services:
  geth-rpc:
    image: devopsnusatech/beone-geth:prod
    command:
      - --syncmode=full
      - --gcmode=archive
      - --nousb
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=eth,net,web3,personal,miner,admin,txpool,debug
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=eth,net,web3,personal,miner,admin,txpool,debug
      - --ws.origins=*
      - --http.vhosts=*
    volumes:
      - geth-data:/root/.ethereum
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # Define unique middlewares
      - "traefik.http.middlewares.geth-rpc-redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.geth-rpc-secure-headers.headers.customresponseheaders.Access-Control-Allow-Origin=*"
      - "traefik.http.middlewares.geth-rpc-secure-headers.headers.customresponseheaders.Access-Control-Allow-Methods=GET, POST, OPTIONS"
      - "traefik.http.middlewares.geth-rpc-secure-headers.headers.customresponseheaders.Access-Control-Allow-Headers=DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
      - "traefik.http.middlewares.geth-rpc-secure-headers.headers.customresponseheaders.Access-Control-Allow-Credentials=true"
      # Define services
      - "traefik.http.services.geth-rpc-service.loadbalancer.server.port=8545"
      - "traefik.http.services.geth-rpc-ws-service.loadbalancer.server.port=8546"
      # HTTP Router (redirects to HTTPS)
      - "traefik.http.routers.geth-rpc-http.rule=Host(`rpc.haidar.fun`)"
      - "traefik.http.routers.geth-rpc-http.entrypoints=web"
      - "traefik.http.routers.geth-rpc-http.middlewares=geth-rpc-redirect-to-https"
      - "traefik.http.routers.geth-rpc-http.service=geth-rpc-service"
      # HTTPS Router for HTTP RPC (port 8545)
      - "traefik.http.routers.geth-rpc-https.rule=Host(`rpc.haidar.fun`)"
      - "traefik.http.routers.geth-rpc-https.entrypoints=websecure"
      - "traefik.http.routers.geth-rpc-https.tls.certresolver=myresolver"
      - "traefik.http.routers.geth-rpc-https.middlewares=geth-rpc-secure-headers"
      - "traefik.http.routers.geth-rpc-https.service=geth-rpc-service"
      # WebSocket Router for port 8546
      - "traefik.http.routers.geth-rpc-ws.rule=Host(`rpcsocket.haidar.fun`)"
      - "traefik.http.routers.geth-rpc-ws.entrypoints=websecure"
      - "traefik.http.routers.geth-rpc-ws.tls.certresolver=myresolver"
      - "traefik.http.routers.geth-rpc-ws.service=geth-rpc-ws-service"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  geth-data:
